import { NgModule } from "@angular/core";
import {
	CommonModule,
        RouterModule,
        ReactiveFormsModule,
        MatAutocompleteModule,
        MatButtonModule,
        MatButtonToggleModule,
        MatCardModule,
        MatCheckboxModule,
        MatChipsModule,
        MatDatepickerModule,
        MatDialogModule,
        MatExpansionModule,
        MatGridListModule,
        MatIconModule,
        MatInputModule,
        MatListModule,
        MatMenuModule,
        MatNativeDateModule,
        MatPaginatorModule,
        MatProgressBarModule,
        MatProgressSpinnerModule,
        MatRadioModule,
        MatRippleModule,
        MatSelectModule,
        MatSidenavModule,
        MatSliderModule,
        MatSlideToggleModule,
        MatSnackBarModule,
        MatSortModule,
        MatTableModule,
        MatTabsModule,
        MatToolbarModule,
        MatTooltipModule,
		MatStepperModule,		
		MatMomentDateModule,	
		MAT_DIALOG_DEFAULT_OPTIONS,
		MatFormFieldModule,
} from "./material.components";

@NgModule({
    imports: [
        MatRadioModule,
        MatFormFieldModule,
        MatInputModule
    ],
	exports: [
		MatTooltipModule,
		MatTabsModule,
		MatTableModule,
		MatPaginatorModule,
		MatButtonModule,
		MatIconModule,
		MatFormFieldModule,
		MatInputModule,
		MatSelectModule,
		MatProgressSpinnerModule,
		MatCardModule,
		MatMomentDateModule,
		MatDatepickerModule,
		MatSortModule,
		MatCheckboxModule,
		MatAutocompleteModule,

		MatPaginatorModule,
		MatMenuModule,
		MatProgressBarModule,
		MatDialogModule,
		MatNativeDateModule,
		MatExpansionModule,
		MatSnackBarModule,

		CommonModule,
        RouterModule,
        ReactiveFormsModule,
        MatButtonModule,
        MatButtonToggleModule,
        MatChipsModule,
        MatDatepickerModule,
        MatGridListModule,
        MatIconModule,
        MatListModule,
        MatRadioModule,
        MatRippleModule,
        MatSidenavModule,
        MatSliderModule,
        MatSlideToggleModule,
        MatSortModule,
        MatTableModule,
        MatTabsModule,
        MatToolbarModule,
        MatTooltipModule,
		MatStepperModule,		
	],
	providers: [
        {
			provide: MAT_DIALOG_DEFAULT_OPTIONS,
			useValue: {
				hasBackdrop: true,
				panelClass: "kt-mat-dialog-container__wrapper",
				height: "auto",
				width: "900px",
			},
		},
    ]
})
export class MaterialModule {}
